name: OSSF Scorecards

permissions: read-all

on:
  workflow_dispatch:
  branch_protection_rule:
  schedule:
    - cron: '0 1 * * 1'
  push:
    branches: [ develop ]

jobs:
  analyze:
    name: Scorecards - Analyze
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write # Needed to upload results to code-scanning dashboard.

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          persist-credentials: false

      - name: Analyze
        uses: ossf/scorecard-action@80e868c13c90f172d68d1f4501dee99e2479f7af
        with:
          results_file: results.sarif
          results_format: sarif
          repo_token: ${{ secrets.SCORECARD_READ_TOKEN }}
          publish_results: true

      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@5f532563584d71fdef14ee64d17bafb34f751ce5
        with:
          sarif_file: results.sarif
